data = read.table("./verification.txt")

pdf("verification.pdf")
plot(data[,1], data[,2], type="l", xlab="Sample size", ylab="", cex.lab=1.3, cex.axis=1.3, ylim=c(-4, 7), lwd=2, col="blue")
par(new=TRUE)
plot(data[,1], data[,3], type="l", xaxt="n", yaxt="n", xlab="", ylab="", col="orange", ylim=c(-4, 7), lwd=2)
par(new=TRUE)
plot(data[,1], data[,4], type="l", xaxt="n", yaxt="n", xlab="", ylab="", col="green", ylim=c(-4, 7), lwd=2)
par(new=TRUE)
plot(data[,1], data[,5], type="l", xaxt="n", yaxt="n", xlab="", ylab="", col="red", ylim=c(-4, 7), lwd=2)
par(new=TRUE)
plot(data[,1], data[,6], type="l", xaxt="n", yaxt="n", xlab="", ylab="", col="purple", ylim=c(-4, 7), lwd=2)
par(new=TRUE)
plot(data[,1], data[,7], type="l", xaxt="n", yaxt="n", xlab="", ylab="", col="brown", ylim=c(-4, 7), lwd=2)
legend("topleft", legend=c("Obs mean TMRCA", "True mean TMRCA", "Obs mean branch length", "True mean branch length", "Obs log(P(0 & 1 merge 1st))", "True log(P(0 & 1 merge 1st))"), col=c("blue", "orange", "green", "red", "purple", "brown"), cex=1.3, lty=rep(1, 6), lwd=2, ncol=2)
dev.off()
